ALTER DATABASE [cdc_testing] SET ALLOW_SNAPSHOT_ISOLATION ON;
ALTER DATABASE [cdc_testing] SET
  CHANGE_TRACKING = ON (
    CHANGE_RETENTION = 2 DAYS ,
    AUTO_CLEANUP = ON
);

ALTER TABLE [cdc_testing].[dbo].[users] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);